### ISSUE TITLE
Crash Introduced in 1.04

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/soni-sori#54]
https://console.firebase.google.com/u/0/project/meraki-c6769/crashlytics/app/android:org.merakilearn/issues/6c87ef9b5bbeaac4e3be7908337dba24?time=last-twenty-four-hours&versions=1.06%20(7)

```
Caused by java.lang.ClassCastException: org.merakilearn.MainActivityArgs cannot be cast to org.merakilearn.OnBoardingActivityArgs
       at org.merakilearn.OnBoardingActivity.onCreate(OnBoardingActivity.kt:76)
       at android.app.Activity.performCreate(Activity.java:7074)
       at android.app.Activity.performCreate(Activity.java:7065)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2796)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2921)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1639)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6662)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

This is the only crash in the build so far.

**Comment by suhaibroomy** [comment]
is it possible that this crashed on my phone??
