### ISSUE TITLE
Stacktrace logs coming from IM Vector 

### ISSUE THREAD

**Issue by aashish-aadarsh** [navgurukul/soni-sori#85]
Please have a look, if this can be ignored safely. Not causing any issue in runtime of application.

/TaskExecutor$execute: Task failed
    ServerError(error=MatrixError(code=M_NOT_FOUND, message=No backup found, consentUri=null, limitType=null, adminUri=null, retryAfterMillis=null, isSoftLogout=false, newLookupPepper=null), httpCode=404)
        at im.vector.matrix.android.internal.network.RetrofitExtensionsKt.toFailure(RetrofitExtensions.kt:90)
        at im.vector.matrix.android.internal.network.RetrofitExtensionsKt.toFailure(RetrofitExtensions.kt:58)
        at im.vector.matrix.android.internal.network.Request.execute(Request.kt:49)
        at im.vector.matrix.android.internal.network.Request$execute$1.invokeSuspend(Unknown Source:11)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: java.lang.RuntimeException: MatrixError(code=M_NOT_FOUND, message=No backup found, consentUri=null, limitType=null, adminUri=null, retryAfterMillis=null, isSoftLogout=false, newLookupPepper=null)
        at im.vector.matrix.android.internal.network.RetrofitExtensionsKt.toFailure(RetrofitExtensions.kt:90) 
        at im.vector.matrix.android.internal.network.RetrofitExtensionsKt.toFailure(RetrofitExtensions.kt:58) 
        at im.vector.matrix.android.internal.network.Request.execute(Request.kt:49) 
        at im.vector.matrix.android.internal.network.Request$execute$1.invokeSuspend(Unknown Source:11) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by suhaibroomy** [comment]
can you share crashlytics link @aashish-aadarsh

**Comment by aashish-aadarsh** [comment]
This was showing in logcat but no crash was observed

**Comment by suhaibroomy** [comment]
Matrix doesn't print logs in release mode. Closing this
